config/routes.rb
Cats99::Application.routes.draw do
  resources :cats
  resources :cat_rental_requests

  root to: 'cats#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :location, :name, :image, :price
  has_attached_file :image
  has_many :cat_rental_requests
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :approved, :cat_id, :rental_end, :rental_start
  belongs_to :cat
  validate :rental_dates_not_overlap

  def rental_dates_not_overlap
     unless CatRentalRequest.where("approved = 't' AND
                            cat_id = ? AND
                            (rental_start >= ? OR
                            rental_end <= ?)",
                            self.cat_id,
                            self.rental_end, self.rental_start).empty?

          errors[:rental_end] << "Someone has this cat."
     end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat_rental_request = CatRentalRequest.all
  end

  def create
    puts params
    @cat_rental_request = CatRentalRequest.new(params[:cat_rental_request])
    if @cat_rental_request.save
      redirect_to cat_path(@cat_rental_request.cat)
    else
      redirect_to new_cat_rental_request_path + "?id=" + params[:cat_rental_request][:cat_id]
    end
  end

  def new
    @cat_id = params[:id]
    @cat_rental_request = CatRentalRequest.new
  end

  def update
    @cat_rental_request = CatRentalRequest.find(params[:id])
    @cat_rental_request.update_attributes(params[:cat_rental_request])
    redirect_to cat_rental_request_path(@cat_rental_request)
  end

  def show
    @cat_rental_request = CatRentalRequest.find(params[:id])
  end

  def edit
    @cat_rental_request = CatRentalRequest.find(params[:id])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def create
    @cat = Cat.new(params[:cat])
    @cat.save

    redirect_to cat_path(@cat)
  end

  def new
    @cat = Cat.new
  end

  def show
    @cat = Cat.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/edit.html.erb
<h1>Cat Rental Request</h1>
<p>for <%= @cat_rental_request.cat.name %></p>
<p>
  Start Date: <%= @cat_rental_request.rental_start %>
</p>
<p>
  End Date: <%= @cat_rental_request.rental_end %>
</p>


<% if @cat_rental_request.approved.nil? %>

<%= form_for(@cat_rental_request) do |f| %>
  Approve?
  <input type="radio" name="cat_rental_request[approved]" value="true">Yes
  <input type="radio" name="cat_rental_request[approved]" value="false">No
  <input type="submit">
<% end %>

<% elsif @cat_rental_request.approved %>
APPROVED!

<% else %>
REJECTED!

<% end %>

app/views/cat_rental_requests/index.html.erb
<h1>Cat Rentals</h1>
<%= "No requests!" if @cat_rental_request.empty? %>
<ul>
  <% @cat_rental_request.each do |request| %>
  <li><%= link_to "Request #{request.id}: #{request.cat.name}", cat_rental_request_path(request) %></li>
  <% end %>
</ul>

<%= link_to  "<< Cats", cats_path %>

app/views/cat_rental_requests/new.html.erb
<%= form_for(@cat_rental_request) do |f| %>

<p>
  <%= f.label :cat_id, "Cat ID" %><br />
  <%= f.text_field :cat_id, size: 5, value: @cat_id, readonly: true %>
  <!--input id="cat_rental_request_cat_id" name="cat_rental_request[cat_id]" size="5" type="text" disabled="disabled" value="<%= @cat_id %>"/-->
</p>
<p>
  <%= f.label :rental_start, "Start Date/Time" %><br />
  <%= f.date_select :rental_start %>
  <%= f.time_select :rental_start, :ignore_date => true  %>
</p>
<p>
  <%= f.label :rental_end, "End Date/Time" %><br />
  <%= f.date_select :rental_end %>
  <%= f.time_select :rental_end, :ignore_date => true  %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/cat_rental_requests/show.html.erb
<h1>Cat Rental Request</h1>

<h1><%= @cat_rental_request.cat.name %> for $<%= @cat_rental_request.cat.price %></h1>
<p><%= image_tag @cat_rental_request.cat.image.url, class: "cat-images" %></p>

<p>
  Start Date: <%= @cat_rental_request.rental_start %>
</p>
<p>
  End Date: <%= @cat_rental_request.rental_end %>
</p>

<% if @cat_rental_request.approved.nil? %>
<%= link_to "Approve/Reject", edit_cat_rental_request_path(@cat_rental_request) %>
<% else %>
Status: <%= @cat_rental_request.approved ? "Approved" : "Rejected" %>
<% end %>

<br>
<br>
<%= link_to "Back", :back %>

app/views/cats/index.html.erb
<h1>Cats</h1>
<%= "No cats!" if @cats.empty? %>

<ul class="thumbnails">
  <% @cats.each do |cat| %>
  <li class="span3">
    <a href="<%= cat_path(cat) %>" class="thumbnail">
      <img src="<%= cat.image %>" alt="">
    </a>
    <h3><%= cat.name %></h3>
  </li>
  <% end %>
</ul>

<%= link_to  "Create Cat", new_cat_path %> <br>
<%= link_to  "Cat Rentals", cat_rental_requests_path %>

app/views/cats/new.html.erb
<%= form_for(@cat, html: {multipart: true}) do |f| %>

<p>
  <%= f.label :image, "Attach Cat" %><br />
  <%= f.file_field :image %>
</p>
<p>
  <%= f.label :name, "Cat name" %><br />
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :location, "Cat location" %><br />
  <%= f.text_field :location %>
</p>
<p>
  <%= f.label :price, "Price per hour" %><br />
  <%= f.text_field :price %>
</p>
<p>
  <%= f.submit %>
  <%= link_to "Cancel", :back, class: "btn" %>
</p>

<% end %>

app/views/cats/show.html.erb
<h1><%= @cat.name %> ONLY $<%= @cat.price %>!!!!!!*</h1>
<p>from <%= @cat.location %></p>

<%= link_to "Rent this cat NOW!!!", new_cat_rental_request_path + "?id=" + @cat.id.to_s%>

<p><%= image_tag @cat.image.url, class: "cat-images" %></p>

<% @cat.cat_rental_requests.each do |request| %>

<p>Start: <%= request.rental_start %></p>
<p>End: <%= request.rental_end %></p>
<p>Status: <%= request.approved.nil? ? 'Awaiting Approval' : (request.approved ? 'Approved' : 'Rejected')%></p>

<% end %>

<small>* per hour</small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats99</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="well well-large" style="margin-top: 50px;">

    <%= yield %>
  </div>
</div>
</body>
</html>